apiVersion: tekton.dev/v1beta1
kind: PipelineResource
metadata:
  name: image
spec:
  type: image
  params:
    - name: url
      value: default-route-openshift-image-registry.apps-crc.testing/tekton-argocd/tutorial-tekton-argocd-code
